services:
  pygeoapi:
    build: .
    ports:
      - "${LARE_API_PORT:-5000}:80"
    environment:
      PYTHONPATH: /pygeoapi

      # Host-visible path used when registering GeoPackage datastores in
      # external (non-container) GeoServer instances.
      LARE_TMPDIR_CONTAINER: /pygeoapi/tmp
      LARE_TMPDIR_HOST: "${LARE_TMPDIR_HOST:-./tmp}"
    volumes:
      - ${LARE_PYGEOAPI_CONFIG:-./pygeoapi-config.yml}:/pygeoapi/local.config.yml:ro
      - ${LARE_APP_CONFIG:-./app.yml}:/pygeoapi/app.yml:rw
      - ${LARE_DATA_DIR:-./data}:/pygeoapi/data:rw
      - ${LARE_TMP_DIR:-./tmp}:/pygeoapi/tmp:rw

