name: lare
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pywps
  - flask
  - rasterio=1.4.4
  - pandas
  - numpy
  - ipykernel
  - geopandas
  - psycopg2-binary
  - sqlalchemy
  - owslib
  - geojson
  - shapely
  - scipy
  - geoserver-restconfig